site_name: TACTICS Simulator
repo_url: https://github.com/WoodOxen/tactics
docs_dir: Docs
edit_uri: 'blob/latest/Docs'
theme: readthedocs

nav:
- Home: 'source/index.md'
# - Manual for Developers:
#   - 'APIs': "dev_apis.md"
